name: dotnet build

on: [push]

jobs:
    build:
      runs-on: ubuntu-20.04
      strategy:
        matrix: 
          dotnet-version: [ '5.0.x' ]
      steps:
      - uses: actions/checkout@v2
      - name: Setup .NET SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Install dependencies
        run: dotnet restore
      - name: Build project
        run: dotnet build --configuration Release --no-restore