name: Caller

on: [push]

jobs:
  build-workflow:
    - uses: actions/checkout@v2
      with:
        repository:  Morinslash/GitHubActions-DotNet-Workflows
        # token: ${{ secrets.GIT_TOKEN }}
        path: .github/actions/category-test-action
    - uses: ./.github/workflows/dotnet-workflow.yaml@master