name: dotnet test

on:
  workflow_run:
    workflows: ["dotnet build"]
    types:
      - completed

jobs:
  unit-test:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-20.04
    strategy:
      matrix: 
        dotnet-version: ['5.0.x']
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: dotnet restore
      - name: Unit tests
        run: dotnet test --filter "Category=UnitTest"
  
  integration-test:
    runs-on: ubuntu-20.04
    needs: unit-test
    strategy:
      matrix:
        dotnet-version: ['5.0.x']
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: dotnet restore
      - name: Unit tests
        run: dotnet test --filter "Category=IntegrationTest"