name: Caller

on: [push]

jobs:
#  build-workflow:
#    uses: morinslash/GitHubActions-DotNet-Workflows/.github/workflows/dotnet-workflow.yaml@master
  docker-workflow:
    uses: morinslash/GitHubActions-DotNet-Workflows/.github/workflows/docker-build.yaml@master
    with:
      context: ./GitHubActions-POC